"""empty message

Revision ID: 07ef8b987e2a
Revises: f93d1b46c26b
Create Date: 2023-09-12 16:20:57.022963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ef8b987e2a'
down_revision = 'f93d1b46c26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plugin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_plugin_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plugin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugin_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
